[package]
name = "authentication-web-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-web = "4.3.0"
chrono = { version = "0.4.22", features = ["serde"] }
dotenv = "0.15.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
config = "0.13.3"
diesel = { version = "2.0.3", features = ["uuid", "r2d2", "postgres"] }
diesel_migrations = "2.0.0"
uuid = { version = "1.3.0", features = ["v4", "serde"] }
parse_duration = "2.1.1"
envconfig = "0.10.0"
google-authenticator = "0.3.0"
magic-crypt = "3.1.12"
actix-cors = "0.6.4"
tokio = {version = "1", features = ["full"]}

# DEPENDENCIES SPECIFIC TO AUTH
actix-web-httpauth = "0.8.0"
argonautica = "0.2.0"
hmac = "0.12.1"
jwt = "0.16.0"
sha2 = "0.10.6"
