---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth2fa-app-deployment
  namespace: dev
  labels:
    app: auth2fa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth2fa-app
  template:
    metadata:
      labels:
        app: auth2fa-app
    spec:
      containers:
      - name: auth2fa-app
        image: "joshuagoldman1994/auth2fa-app:2.0.0-t23"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth2fa-app-service
  namespace: dev
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: auth2fa-app

            
